export default {
    GET_STATISTIC_ACTION: 'GET_STATISTIC_ACTION',
    GET_STATISTIC_REQUEST: 'GET_STATISTIC_REQUEST',
    GET_STATISTIC_SUCCESS: 'GET_STATISTIC_SUCCESS',
    GET_STATISTIC_ERROR: 'GET_STATISTIC_ERROR',
    CREATE_VOTE_ACTION: 'CREATE_VOTE_ACTION',
    CREATE_VOTE_SUCCESS: 'CREATE_VOTE_SUCCESS',
    CREATE_VOTE_ERROR: 'CREATE_VOTE_ERROR',
    GET_LOGS_ACTION: 'GET_LOGS_ACTION',
    GET_LOGS_SUCCESS: 'GET_LOGS_SUCCESS',
}